# Generated by Django 4.1.4 on 2023-03-25 14:18

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('caption', models.TextField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=22, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Country Name')),
                ('image', models.ImageField(default='images/default/defaultImage.jpg', upload_to='images/%y/%m/%d', verbose_name='Photo')),
                ('activeState', models.BooleanField(default=True, verbose_name='Active State')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='City Name')),
                ('caption', models.TextField(null=True, validators=[pages.models.validate_min_length, pages.models.validate_max_length], verbose_name='Caption')),
                ('image', models.ImageField(default='images/default/defaultImage.jpg', upload_to='images/%y/%m/%d', verbose_name='Image')),
                ('exchangeRate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Exchage Rate')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating')),
                ('activeState', models.BooleanField(default=True, verbose_name='Active State')),
                ('inWishlist', models.BooleanField(default=False, verbose_name='in Wishlist')),
                ('mapSrc', models.TextField(null=True, verbose_name='Map Source')),
                ('activities', models.ManyToManyField(to='pages.activity')),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', to_field='type')),
                ('country', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.country', to_field='name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-rating'],
            },
        ),
    ]
