# Generated by Django 4.1.4 on 2022-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-rating'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='catigory',
        ),
        migrations.AddField(
            model_name='city',
            name='category',
            field=models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Leisure Tourism', 'Leisure Tourism'), ('Archaeological Tourism', 'Archaeological Tourism'), ('Religious Tourism', 'Religious Tourism')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, verbose_name='City Name'),
        ),
    ]
