# Generated by Django 4.1.4 on 2023-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cityName',
            field=models.CharField(default='all', max_length=25, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='images/default/defaultImage.jpg', upload_to='images/%y/%m/%d', verbose_name='Image'),
        ),
    ]
