# Generated by Django 4.1.4 on 2023-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_activity_cityname_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_name', models.CharField(max_length=50, unique=True)),
                ('caption', models.TextField(blank=True, unique=True)),
                ('cityName', models.CharField(default='all', max_length=25, verbose_name='City Name')),
                ('image', models.ImageField(default='images/default/defaultImage.jpg', upload_to='images/%y/%m/%d', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='restaurants',
            field=models.ManyToManyField(to='pages.restaurants'),
        ),
    ]
