# Generated by Django 4.1.4 on 2023-02-08 12:39

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_city_options_remove_city_catigory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='caption',
            field=models.CharField(max_length=100, null=True, validators=[pages.models.validate_min_length], verbose_name='Caption'),
        ),
    ]
