# Generated by Django 4.1.4 on 2023-02-08 12:49

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_city_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='caption',
            field=models.TextField(null=True, validators=[pages.models.validate_min_length, pages.models.validate_max_length], verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=25, verbose_name='City Name'),
        ),
    ]
