# Generated by Django 4.1.4 on 2023-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_restaurants_city_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('caption', models.TextField(blank=True, unique=True)),
                ('cityName', models.CharField(default='all', max_length=25, verbose_name='City Name')),
                ('image', models.ImageField(default='images/default/defaultImage.jpg', upload_to='images/%y/%m/%d', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='R_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
