# Generated by Django 4.1.4 on 2023-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_hotels_alter_restaurants_r_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hotels',
            field=models.ManyToManyField(to='pages.hotels'),
        ),
    ]
