# Generated by Django 4.1.4 on 2023-04-09 21:11

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_city_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='activities',
            field=models.ManyToManyField(blank=True, to='pages.activity'),
        ),
        migrations.AlterField(
            model_name='city',
            name='caption',
            field=models.TextField(help_text='Caption length must be between 40 and 2000 characters', null=True, validators=[pages.models.validate_min_length, pages.models.validate_max_length], verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='city',
            name='exchangeRate',
            field=models.DecimalField(decimal_places=2, help_text='The value of the local currency against one USD', max_digits=6, verbose_name='Exchage Rate'),
        ),
        migrations.AlterField(
            model_name='city',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='pages.hotels'),
        ),
        migrations.AlterField(
            model_name='city',
            name='mapSrc',
            field=models.TextField(blank=True, verbose_name='Map Source'),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Must be from 0 to 5', max_digits=2, max_length=5, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='city',
            name='restaurants',
            field=models.ManyToManyField(blank=True, to='pages.restaurants'),
        ),
    ]
