# Generated by Django 4.1.4 on 2023-04-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_activity_type_alter_city_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.category', to_field='type'),
        ),
    ]
