# Generated by Django 4.1.4 on 2023-02-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user_delete_signin_alter_city_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
