# Generated by Django 4.1.4 on 2023-04-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
