# Generated by Django 4.1.4 on 2023-02-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_category_remove_city_category_city_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='categories',
        ),
        migrations.AddField(
            model_name='city',
            name='category',
            field=models.CharField(blank=True, choices=[('Not Specified', 'Not Specified'), ('Leisure Tourism', 'Leisure Tourism'), ('Archaeological Tourism', 'Archaeological Tourism'), ('Religious Tourism', 'Religious Tourism')], max_length=22, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
