# Generated by Django 4.1.4 on 2023-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_city_categories_city_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Name'),
        ),
    ]
