# Generated by Django 4.1.4 on 2023-04-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_city_inwishlist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='city',
            new_name='cities',
        ),
    ]
