# Generated by Django 4.1.4 on 2023-02-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
