# Generated by Django 4.1.4 on 2023-02-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_project_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
