# Generated by Django 4.1.4 on 2023-04-26 21:49

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(help_text='Description length must be between 40 and 2000 characters', null=True, validators=[pages.models.validate_min_length, pages.models.validate_max_length], verbose_name='Description'),
        ),
    ]
